version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # replace with your MySQL root password
      MYSQL_DATABASE: clickops_db
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./backend  # Corrected path
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root  # Make sure this matches MYSQL_ROOT_PASSWORD

volumes:
  db_data:

